-- run as owner
DROP TABLE OLDKEYS CASCADE CONSTRAINTS;
DROP SEQUENCE oldkeys_seq;

CREATE TABLE oldkeys (
  ID            NUMBER(10)   NOT NULL,
  OLDSERIALKEY  VARCHAR2(50) NOT NULL,
  DEACTIVATED   NUMBER(1) DEFAULT 0 NOT NULL,
  CREATED       TIMESTAMP    NOT NULL,
  CREATOR       VARCHAR2(50) NOT NULL,
  UPDATED       TIMESTAMP    NULL,
  UPDATOR       VARCHAR2(50) NULL,
  PRIMARY KEY (ID)
);
ALTER TABLE oldkeys
  ADD CONSTRAINT oldkeys_0_uk UNIQUE (OLDSERIALKEY);
CREATE SEQUENCE oldkeys_seq
  START WITH 1;

GRANT SELECT ON oldkeys TO license_ro_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON oldkeys TO license_rw_role;
GRANT SELECT ON oldkeys_seq TO license_rw_role;

DROP TABLE issue CASCADE CONSTRAINTS;
DROP SEQUENCE issue_seq;

CREATE TABLE issue (
  ID            NUMBER(10)          NOT NULL,
  BRANCH        VARCHAR2(50)        NOT NULL,
  DOMAINUSER    VARCHAR2(50)        NOT NULL,
  OLDSERIALKEY  VARCHAR2(50)        NULL,
  DISTRIBUTOR   NUMBER(10)          NULL,
  SEQUENCE      NUMBER(10)          NULL,
  NOOLDLICENSE  NUMBER(1) DEFAULT 0 NOT NULL,
  LICENSEFILE   VARCHAR2(70)        NULL,
  SERIALKEY     VARCHAR2(500)       NULL,
  CREATED       TIMESTAMP           NOT NULL,
  CREATOR       VARCHAR2(50)        NOT NULL,
  UPDATED       TIMESTAMP           NULL,
  UPDATOR       VARCHAR2(50)        NULL,
  PRIMARY KEY (ID)
);

ALTER TABLE issue
  ADD CONSTRAINT p_issue_fk FOREIGN KEY (OLDSERIALKEY) REFERENCES oldkeys (OLDSERIALKEY);
ALTER TABLE issue
  ADD CONSTRAINT issue_0_uk UNIQUE (DOMAINUSER);
CREATE SEQUENCE issue_seq
  START WITH 1;

GRANT SELECT ON issue TO license_ro_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON issue TO license_rw_role;
GRANT SELECT ON issue_seq TO license_rw_role;

DROP TABLE verify CASCADE CONSTRAINTS;
DROP SEQUENCE verify_seq;

CREATE TABLE verify (
  ID            NUMBER(10)   NOT NULL,
  LICENSEFILE   VARCHAR2(70) NOT NULL,
  CREATED       TIMESTAMP    NOT NULL,
  CREATOR       VARCHAR2(50) NOT NULL,
  PRIMARY KEY (ID)
);
CREATE SEQUENCE verify_seq
  START WITH 1;

GRANT SELECT ON verify TO license_ro_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON verify TO license_rw_role;
GRANT SELECT ON verify_seq TO license_rw_role;

